### ISSUE TITLE
其他错误： 'fileEntry' 似乎是ydnote_dir_id获取失败，目前有道云改了界面，是否因此无法获取目录？大佬有时间看看更新一下吗

### ISSUE THREAD

**Issue by guyeu9** [DeppWang/youdaonote-pull#102]
C:\Users\Administrator\youdaonote-pull>python pull.py
本次使用 Cookies 登录
其他错误： 'fileEntry'
Traceback (most recent call last):
  File "pull.py", line 784, in <module>
    ydnote_dir_id, error_msg = youdaonote_pull.get_ydnote_dir_id()
  File "pull.py", line 451, in get_ydnote_dir_id
    return self._get_ydnote_dir_id(ydnote_dir=config_dict['ydnote_dir'])
  File "pull.py", line 525, in _get_ydnote_dir_id
    root_dir_id = root_dir_info['fileEntry']['id']
KeyError: 'fileEntry'
已终止执行

**Comment by DeppWang** [comment]
我使用原来旧的 Cookies 也有这个问题，使用最新的 Cookies 没有问题，可尝试使用最新的 Cookies。

**Comment by leonvogle** [comment]
更新一下cookie就可以了
