### ISSUE TITLE
登录报错，AttributeError: module 'requests.exceptions' has no attribute 'ProxyError'

### ISSUE THREAD

**Issue by justdomyself** [DeppWang/youdaonote-pull#103]
我看cookies比之前多了好多，多了YNOTE_PERS项 ，是不是程序也得把这个加进去啊

报错信息如下：

D:\python.exe E:/nas/2023/youdaonote-pull/pull.py
本次使用 Cookies 登录
Traceback (most recent call last):
  File "D:\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 536, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "D:\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 298, in _get_conn
    return conn or self._new_conn()
  File "D:\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 718, in _new_conn
    return self._prepare_conn(connection)
  File "D:\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 685, in _prepare_conn
    connection.connect()
  File "D:\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 138, in connect
    match_hostname(self.sock.getpeercert(),
  File "D:\lib\site-packages\requests\packages\urllib3\packages\ssl_match_hostname\__init__.py", line 89, in match_hostname
    raise CertificateError("hostname %r "
requests.packages.urllib3.packages.ssl_match_hostname.CertificateError: hostname '127.0.0.1' doesn't match either of '*.youdao.com', 'youdao.com'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\lib\site-packages\requests\adapters.py", line 309, in send
    resp = conn.urlopen(
  File "D:\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 578, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: hostname '127.0.0.1' doesn't match either of '*.youdao.com', 'youdao.com'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/nas/2023/youdaonote-pull/pull.py", line 784, in <module>
    ydnote_dir_id, error_msg = youdaonote_pull.get_ydnote_dir_id()
  File "E:/nas/2023/youdaonote-pull/pull.py", line 451, in get_ydnote_dir_id
    return self._get_ydnote_dir_id(ydnote_dir=config_dict['ydnote_dir'])
  File "E:/nas/2023/youdaonote-pull/pull.py", line 524, in _get_ydnote_dir_id
    root_dir_info = self.youdaonote_api.get_root_dir_info_id()
  File "E:/nas/2023/youdaonote-pull/pull.py", line 393, in get_root_dir_info_id
    return self.http_post(self.ROOT_ID_URL.format(cstk=self.cstk), data=data).json()
  File "E:/nas/2023/youdaonote-pull/pull.py", line 374, in http_post
    return self.session.post(url, data=data, files=files)
  File "D:\lib\site-packages\requests\sessions.py", line 399, in post
    return self.request('POST', url, data=data, **kwargs)
  File "D:\lib\site-packages\requests\sessions.py", line 357, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\lib\site-packages\requests\sessions.py", line 460, in send
    r = adapter.send(request, **kwargs)
  File "D:\lib\site-packages\requests\adapters.py", line 358, in send
    raise SSLError(e)
requests.exceptions.SSLError: hostname '127.0.0.1' doesn't match either of '*.youdao.com', 'youdao.com'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/nas/2023/youdaonote-pull/pull.py", line 790, in <module>
    except requests.exceptions.ProxyError as proxyErr:
AttributeError: module 'requests.exceptions' has no attribute 'ProxyError'

进程已结束,退出代码1

**Comment by justdomyself** [comment]
找到原因，requests的版本过低，升级为2.22就好了
