### ISSUE TITLE
pip install -r requirements.txt错误

### ISSUE THREAD

**Issue by leonvogle** [DeppWang/youdaonote-pull#104]
`pip install -r requirements.txt

错误信息提示

ERROR: Exception:
Traceback (most recent call last):
  File "D:\CommandTool\python\lib\site-packages\pip\_internal\cli\base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
  File "D:\CommandTool\python\lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "D:\CommandTool\python\lib\site-packages\pip\_internal\commands\install.py", line 342, in run
    reqs = self.get_requirements(args, options, finder, session)
  File "D:\CommandTool\python\lib\site-packages\pip\_internal\cli\req_command.py", line 433, in get_requirements
    for parsed_req in parse_requirements(
  File "D:\CommandTool\python\lib\site-packages\pip\_internal\req\req_file.py", line 148, in parse_requirements
    for parsed_line in parser.parse(filename, constraint):
  File "D:\CommandTool\python\lib\site-packages\pip\_internal\req\req_file.py", line 335, in parse
    yield from self._parse_and_recurse(filename, constraint)
  File "D:\CommandTool\python\lib\site-packages\pip\_internal\req\req_file.py", line 340, in _parse_and_recurse
    for line in self._parse_file(filename, constraint):
  File "D:\CommandTool\python\lib\site-packages\pip\_internal\req\req_file.py", line 371, in _parse_file
    _, content = get_file_content(filename, self._session)
  File "D:\CommandTool\python\lib\site-packages\pip\_internal\req\req_file.py", line 549, in get_file_content
    content = auto_decode(f.read())
  File "D:\CommandTool\python\lib\site-packages\pip\_internal\utils\encoding.py", line 34, in auto_decode
    return data.decode(
UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 54: illegal multibyte sequence`

**Comment by leonvogle** [comment]
找到问题所在了，requirements.txt文件内容如下
requests==2.22.0
markdownify==0.5.1  # 用于 html 转化为 md
Brotli==1.0.9  # 用于还原有道云笔记网络请求 response br 类型压缩
去掉#及后面的内容就可以了，看来pip无法正确识别#作为注释啊

**Comment by DeppWang** [comment]
Windows 可能无法识别 requirements.txt 中的注释， macOS 是没有问题的，我已将注释删除，感谢提出问题
