### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by xiao468657802** [DeppWang/youdaonote-pull#128]
帅哥，已star ,有空帮忙看下这个是什么报错

Traceback (most recent call last):
  File "D:\Software\pythondata\venv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\sss\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\sss\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\sss\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
json.decoder.JSONDecodeError： 期望值： 第 1 行第 1 列 （char 0）
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Software\pythondata\youdaonote-pull-master\pull.py", line 802, in <module>
    youdaonote_pull.pull_dir_by_id_recursively(ydnote_dir_id, youdaonote_pull.root_local_dir)
  File "D:\Software\pythondata\youdaonote-pull-master\pull.py", line 477, in pull_dir_by_id_recursively
    self.pull_dir_by_id_recursively(id, sub_dir)
  File "D:\Software\pythondata\youdaonote-pull-master\pull.py", line 477, in pull_dir_by_id_recursively
    self.pull_dir_by_id_recursively(id, sub_dir)
  File "D:\Software\pythondata\youdaonote-pull-master\pull.py", line 464, in pull_dir_by_id_recursively
    dir_info = self.youdaonote_api.get_dir_info_by_id(dir_id)
  File "D:\Software\pythondata\youdaonote-pull-master\pull.py", line 412, in get_dir_info_by_id
    return self.http_get(url).json()
  File "D:\Software\pythondata\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
其他错误： Expecting value: line 1 column 1 (char 0)
requests.exceptions.JSONDecodeError： 期望值： 第 1 行第 1 列 （char 0）
其他错误： 期望值：第 1 行第 1 列（字符 0）

已终止执行

Process finished with exit code 1

**Comment by DeppWang** [comment]
根据错误提示看不出来是什么问题，如果解决可以反馈下，给其他人提供下解决思路
