### ISSUE TITLE
运行错误，cookie

### ISSUE THREAD

**Issue by BruceAE86** [DeppWang/youdaonote-pull#150]
请在 Issues 中搜索是否有同样的问题，如果没有，再提问

Issue 需要包含以下信息：
操作系统版本：如 macOS 14.6.1
使用的是简单版本
如果文档下载后格式有问题，请贴出有文档分享链接。
Traceback (most recent call last):
  File "pull.py", line 352, in <module>
  File "pull.py", line 147, in get_ydnote_dir_id
  File "pull.py", line 114, in _get_ydnote_dir_id
KeyError: 'fileEntry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging/__init__.py", line 1100, in emit
  File "logging/__init__.py", line 943, in format
  File "logging/__init__.py", line 678, in format
  File "logging/__init__.py", line 368, in getMessage
TypeError: not all arguments converted during string formatting
Call stack:
  File "pull.py", line 374, in <module>
  File "logging/__init__.py", line 2138, in info
  File "logging/__init__.py", line 1477, in info
  File "logging/__init__.py", line 1624, in _log
  File "logging/__init__.py", line 1634, in handle
  File "logging/__init__.py", line 1696, in callHandlers
  File "logging/__init__.py", line 968, in handle
  File "logging/__init__.py", line 1218, in emit
  File "logging/__init__.py", line 1108, in emit
Message: 'Cookies 可能已过期！其他错误：'
Arguments: ("'fileEntry'",)
--- Logging error ---
Traceback (most recent call last):
  File "pull.py", line 352, in <module>
  File "pull.py", line 147, in get_ydnote_dir_id
  File "pull.py", line 114, in _get_ydnote_dir_id
KeyError: 'fileEntry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging/__init__.py", line 1100, in emit
  File "logging/__init__.py", line 943, in format
  File "logging/__init__.py", line 678, in format
  File "logging/__init__.py", line 368, in getMessage
TypeError: not all arguments converted during string formatting
Call stack:
  File "pull.py", line 374, in <module>
  File "logging/__init__.py", line 2138, in info
  File "logging/__init__.py", line 1477, in info
  File "logging/__init__.py", line 1624, in _log
  File "logging/__init__.py", line 1634, in handle
  File "logging/__init__.py", line 1696, in callHandlers
  File "logging/__init__.py", line 968, in handle
  File "logging/__init__.py", line 1108, in emit
Message: 'Cookies 可能已过期！其他错误：'
Arguments: ("'fileEntry'",)
Traceback (most recent call last):
  File "pull.py", line 352, in <module>
  File "pull.py", line 147, in get_ydnote_dir_id
  File "pull.py", line 114, in _get_ydnote_dir_id
KeyError: 'fileEntry'
2024/09/03 15:16:15  INFO MainProcess-MainThread-8634872384 pull.py:376 <module>   : 已终止执行

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[进程已完成]

**Comment by BruceAE86** [comment]
已解决

**Comment by Xiamu-ssr** [comment]
请问是如何解决的？
