### ISSUE TITLE
fileEntry报错

### ISSUE THREAD

**Issue by isofun** [DeppWang/youdaonote-pull#99]
屏幕输出如下：
本次使用 Cookies 登录
其他错误： 'fileEntry'
Traceback (most recent call last):
  File "pull.py", line 784, in <module>
    ydnote_dir_id, error_msg = youdaonote_pull.get_ydnote_dir_id()
  File "pull.py", line 451, in get_ydnote_dir_id
    return self._get_ydnote_dir_id(ydnote_dir=config_dict['ydnote_dir'])
  File "pull.py", line 525, in _get_ydnote_dir_id
    root_dir_id = root_dir_info['fileEntry']['id']
KeyError: 'fileEntry'
已终止执行

**Comment by isofun** [comment]
cookie文件名我搞错了。。。。
